version: '3.8'

services:
  homeassistant-dev:
    container_name: haanim-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8123:8123'
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=UTC
    volumes:
      # Mount HAAnim for live development
      - ./custom_components/haanim:/config/custom_components/haanim:z
      # Mount HAAnim scripts folder
      - ./podman/container-config/haanim:/config/haanim:z
