"""Type stubs for the HAAnim virtual module.

This file provides type hints for the 'haanim' module that is available
to user automation scripts. It allows IDE features like autocompletion,
type checking, and documentation to work properly.

Note: This module is virtual and provided by the HAAnim integration at runtime.
The actual implementations are in custom_components/haanim/decorators.py.

Auto-generated by: uv run python scripts/generate_stubs.py
"""

from typing import Any, Callable, TypeVar, overload

F = TypeVar("F", bound=Callable[..., Any])

# =============================================================================
# Decorators
# =============================================================================


@overload
def scene(func: F) -> F:
    """Mark a function as a scene (no arguments)."""
    ...


@overload
def scene(
    name: str | None = None,
    *,
    description: str | None = None,
) -> Callable[[F], F]:
    """Expose a function as a scene with configuration."""
    ...


def scene(
    name_or_func: str | F | None = None,
    *,
    description: str | None = None,
) -> F | Callable[[F], F]:
    """Decorator to mark a function as a scene, manually executable from the UI.

    When a function is decorated with @scene, it becomes available in the HAAnim
    UI for manual execution. Manual execution bypasses all trigger constraints.

    Args:
        name_or_func: Optional display name for the scene, or the function if
            used without arguments.
        description: Optional description of what the scene does.

    Returns:
        Decorated function or decorator.

    Example:
        @scene
        def turn_on_lights():
            pass

        @scene("Morning Routine")
        def morning_routine():
            pass

        @scene("Evening Scene", description="Activates evening lighting")
        @time_trigger("sunset")
        def evening_scene():
            pass
    """
    ...


@overload
def service(func: F) -> F:
    """Mark a function as a service (no arguments)."""
    ...


@overload
def service(
    name: str | None = None,
    *,
    schema: dict[str, Any] | None = None,
    description: str | None = None,
) -> Callable[[F], F]:
    """Expose a function as a service with configuration."""
    ...


def service(
    name_or_func: str | F | None = None,
    *,
    schema: dict[str, Any] | None = None,
    description: str | None = None,
) -> F | Callable[[F], F]:
    """Decorator to expose a function as a Home Assistant service.

    Args:
        name_or_func: Optional service name, or the function if used without arguments.
        schema: Optional voluptuous schema for service parameters.
        description: Optional description for the service.

    Returns:
        Decorated function or decorator.

    Example:
        @service
        def my_custom_service(entity_id: str):
            pass

        @service("custom_action", description="Does something custom")
        def custom_action(target: str, value: int):
            pass
    """
    ...


def state_trigger(
    *trigger_exprs: str,
    state_hold: float | None = None,
    state_check_now: bool = False,
    watch: list[str] | None = None,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to trigger a function when state conditions are met.

    Args:
        trigger_exprs: One or more state expressions that trigger the function.
            Examples: "sensor.temperature > 25", "binary_sensor.motion == 'on'"
        state_hold: Optional seconds the condition must remain true before triggering.
        state_check_now: If True, check the condition immediately on script load.
        watch: Optional list of entity IDs to watch for changes.
        **kwargs: Additional trigger configuration.

    Returns:
        Decorator function.

    Example:
        @state_trigger("sensor.temperature > 25", state_hold=60)
        def handle_high_temp():
            pass

        @state_trigger(
            "binary_sensor.motion == 'on'",
            "binary_sensor.door == 'open'",
        )
        def handle_activity():
            pass
    """
    ...


def time_trigger(
    *trigger_specs: str,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to trigger a function at specific times.

    Args:
        trigger_specs: One or more time specifications. Supports:
            - Cron expressions: "cron(0 8 * * *)" (8 AM daily)
            - Time of day: "time(08:00:00)"
            - Periods: "period(0:00, 1 hour)" (every hour)
            - Sunrise/sunset: "sunrise", "sunset", "sunrise + 30m"
            - Startup: "startup" (run when HA starts)
        **kwargs: Additional trigger configuration.

    Returns:
        Decorator function.

    Example:
        @time_trigger("cron(0 8 * * *)")  # 8 AM daily
        def morning_routine():
            pass

        @time_trigger("sunrise + 30m", "sunset - 15m")
        def lighting_automation():
            pass
    """
    ...


def event_trigger(
    event_type: str,
    *,
    event_data: dict[str, Any] | None = None,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to trigger a function when a Home Assistant event fires.

    Args:
        event_type: The event type to listen for (e.g., "state_changed", "call_service").
        event_data: Optional filter for event data fields.
        **kwargs: Additional trigger configuration.

    Returns:
        Decorator function.

    Example:
        @event_trigger("custom_event", event_data={"action": "button_press"})
        def handle_button():
            pass
    """
    ...


def time_active(
    *time_specs: str,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to constrain when a triggered function can run.

    This decorator adds time-based constraints. The function will only
    execute if the current time matches the specification. Does NOT
    apply to manual execution via @scene.

    Args:
        time_specs: Time specifications for when the function is active.
            Examples: "range(sunrise, sunset)", "range(08:00, 17:00)"
        **kwargs: Additional configuration.

    Returns:
        Decorator function.

    Example:
        @time_active("range(sunset, sunrise)")
        @state_trigger("binary_sensor.motion == 'on'")
        def night_motion_light():
            pass
    """
    ...


def state_active(
    *state_exprs: str,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to constrain when a triggered function can run based on state.

    This decorator adds state-based constraints. The function will only
    execute if all state expressions evaluate to true. Does NOT apply
    to manual execution via @scene.

    Args:
        state_exprs: State expressions that must be true.
            Examples: "input_boolean.automation_enabled == 'on'"
        **kwargs: Additional configuration.

    Returns:
        Decorator function.

    Example:
        @state_active("input_boolean.night_mode == 'on'")
        @state_trigger("binary_sensor.motion == 'on'")
        def night_only_automation():
            pass
    """
    ...




# =============================================================================
# Built-in globals available in HAAnim scripts
# These are injected into the script's namespace at runtime.
# =============================================================================

# Note: The following are NOT part of the 'haanim' module but are available
# as global variables in your scripts. They are documented here for reference.
#
# log: logging.Logger           - Logger instance for your script
# log_debug: Callable           - Shortcut for log.debug()
# log_info: Callable            - Shortcut for log.info()
# log_warning: Callable         - Shortcut for log.warning()
# log_error: Callable           - Shortcut for log.error()
# sleep: Callable[[float], Awaitable[None]]  - asyncio.sleep for delays
# hass: HomeAssistant           - Home Assistant instance (when available)
# state: StateManager           - Access entity states (when available)
