"""Type stubs for the HAAnim virtual module.

This file provides type hints for the 'haanim' module that is available
to user automation scripts. It allows IDE features like autocompletion,
type checking, and documentation to work properly.

Note: This module is virtual and provided by the HAAnim integration at runtime.
The actual implementations are in custom_components/haanim/decorators.py.

Auto-generated by: uv run python scripts/generate_stubs.py
"""
# pyright: reportUnusedParameter=false
# pyright: reportUnnecessaryTypeIgnoreComment=false
# pyright: reportUnusedExpression=false
# pylint: disable=unused-argument,unnecessary-ellipsis

from typing import Any, Callable, TypeVar, overload

F = TypeVar("F", bound=Callable[..., Any])

# =============================================================================
# Decorators
# =============================================================================

@overload
def action(func: F) -> F:
    """Mark a function as an action (no arguments)."""
    ...

@overload
def action(
    name: str | None = None,
    *,
    description: str | None = None,
    queue: bool = False,
    queue_timeout: float = 10.0,
    preempt: bool = False,
) -> Callable[[F], F]:
    """Expose a function as an action with configuration."""
    ...

def action(
    name_or_func: str | F | None = None,
    *,
    description: str | None = None,
    queue: bool = False,
    queue_timeout: float = 10.0,
    preempt: bool = False,
) -> F | Callable[[F], F]:
    """Decorator to add metadata and flow control to actions.

    Functions with triggers are automatically actions and callable from the UI.
    The @action decorator is optional but allows you to:
    - Provide a custom display name and description
    - Configure queuing behavior for busy scripts
    - Enable preemption to cancel running actions

    Note: Functions with only triggers (no @action) are still callable from the UI
    but use default settings (no queue, no preempt, function name as display name).

    Args:
        name_or_func: Optional display name for the action, or the function if
            used without arguments.
        description: Optional description of what the action does.
        queue: If True, queue the action when the script is busy instead of
            raising ActionBusyError. The action will run after the current
            action completes.
        queue_timeout: Timeout in seconds for queued actions. If the action
            is not processed within this time, it will be cancelled with
            ActionQueueTimeoutError. Set to 0 to wait indefinitely.
        preempt: If True, cancel any currently running action and run this one
            immediately. Takes precedence over queue. Use with caution as it
            may leave the system in an unexpected state.

    Returns:
        Decorated function or decorator.

    Example:
        # Triggered function (automatically an action)
        @time_trigger("sunset")
        def evening_lights():
            pass

        # Manual action only (no triggers)
        @action
        def turn_on_lights():
            pass

        # Triggered with custom metadata
        @action("Evening Scene", description="Activates evening lighting")
        @time_trigger("sunset")
        def evening_action():
            pass

        # Triggered with queue behavior
        @action(queue=True, queue_timeout=30.0)
        @state_trigger("sensor.motion == 'on'")
        def motion_action():
            pass

        # Emergency action with preemption
        @action(preempt=True)
        def emergency_stop():
            pass
    """
    ...

@overload
def service(func: F) -> F:
    """Mark a function as a service (no arguments)."""
    ...

@overload
def service(
    name: str | None = None,
    *,
    schema: dict[str, Any] | None = None,
    description: str | None = None,
) -> Callable[[F], F]:
    """Expose a function as a service with configuration."""
    ...

def service(
    name_or_func: str | F | None = None,
    *,
    schema: dict[str, Any] | None = None,
    description: str | None = None,
) -> F | Callable[[F], F]:
    """Decorator to expose a function as a Home Assistant service.

    Args:
        name_or_func: Optional service name, or the function if used without arguments.
        schema: Optional voluptuous schema for service parameters.
        description: Optional description for the service.

    Returns:
        Decorated function or decorator.

    Example:
        @service
        def my_custom_service(entity_id: str):
            pass

        @service("custom_action", description="Does something custom")
        def custom_action(target: str, value: int):
            pass
    """
    ...

def state_trigger(
    *trigger_exprs: str,
    state_hold: float | None = None,
    state_check_now: bool = False,
    watch: list[str] | None = None,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to trigger a function when state conditions are met.

    Args:
        trigger_exprs: One or more state expressions that trigger the function.
            Examples: "sensor.temperature > 25", "binary_sensor.motion == 'on'"
        state_hold: Optional seconds the condition must remain true before triggering.
        state_check_now: If True, check the condition immediately on script load.
        watch: Optional list of entity IDs to watch for changes.
        **kwargs: Additional trigger configuration.

    Returns:
        Decorator function.

    Example:
        @state_trigger("sensor.temperature > 25", state_hold=60)
        def handle_high_temp():
            pass

        @state_trigger(
            "binary_sensor.motion == 'on'",
            "binary_sensor.door == 'open'",
        )
        def handle_activity():
            pass
    """
    ...

def time_trigger(
    *trigger_specs: str,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to trigger a function at specific times.

    Args:
        trigger_specs: One or more time specifications. Supports:
            - Cron expressions: "cron(0 8 * * *)" (8 AM daily)
            - Time of day: "time(08:00:00)"
            - Periods: "period(0:00, 1 hour)" (every hour)
            - Sunrise/sunset: "sunrise", "sunset", "sunrise + 30m"
            - Startup: "startup" (run when HA starts)
        **kwargs: Additional trigger configuration.

    Returns:
        Decorator function.

    Example:
        @time_trigger("cron(0 8 * * *)")  # 8 AM daily
        def morning_routine():
            pass

        @time_trigger("sunrise + 30m", "sunset - 15m")
        def lighting_automation():
            pass
    """
    ...

def event_trigger(
    event_type: str,
    *,
    event_data: dict[str, Any] | None = None,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to trigger a function when a Home Assistant event fires.

    Args:
        event_type: The event type to listen for (e.g., "state_changed", "call_service").
        event_data: Optional filter for event data fields.
        **kwargs: Additional trigger configuration.

    Returns:
        Decorator function.

    Example:
        @event_trigger("custom_event", event_data={"action": "button_press"})
        def handle_button():
            pass
    """
    ...

def time_active(
    *time_specs: str,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to constrain when a triggered function can run.

    This decorator adds time-based constraints. The function will only
    execute if the current time matches the specification. Does NOT
    apply to manual execution via @action.

    Args:
        time_specs: Time specifications for when the function is active.
            Examples: "range(sunrise, sunset)", "range(08:00, 17:00)"
        **kwargs: Additional configuration.

    Returns:
        Decorator function.

    Example:
        @time_active("range(sunset, sunrise)")
        @state_trigger("binary_sensor.motion == 'on'")
        def night_motion_light():
            pass
    """
    ...

def state_active(
    *state_exprs: str,
    **kwargs: Any,
) -> Callable[[F], F]:
    """Decorator to constrain when a triggered function can run based on state.

    This decorator adds state-based constraints. The function will only
    execute if all state expressions evaluate to true. Does NOT apply
    to manual execution via @action.

    Args:
        state_exprs: State expressions that must be true.
            Examples: "input_boolean.automation_enabled == 'on'"
        **kwargs: Additional configuration.

    Returns:
        Decorator function.

    Example:
        @state_active("input_boolean.night_mode == 'on'")
        @state_trigger("binary_sensor.motion == 'on'")
        def night_only_automation():
            pass
    """
    ...

def startup(func: F) -> F:
    """Decorator to mark a function as a startup handler.

    Functions decorated with @startup are called once when the script is loaded
    and Home Assistant has started. Only one startup handler per script is allowed.
    If multiple are defined, only the last one will be executed.

    Startup handlers:
    - Run after the script is fully loaded and parsed
    - Are executed through the action worker pool (count toward concurrency limits)
    - Should complete quickly to not delay loading of other scripts
    - Cannot be triggered manually from the UI

    Args:
        func: The function to mark as a startup handler.

    Returns:
        The decorated function.

    Example:
        @startup
        async def on_startup():
            log_info("Script initialized!")
            # Perform one-time setup tasks

        @startup
        def sync_startup():
            # Sync functions are also supported
            pass
    """
    ...

def shutdown(func: F) -> F:
    """Decorator to mark a function as a shutdown handler.

    Functions decorated with @shutdown are called when the script is being unloaded,
    reloaded, or when Home Assistant is stopping. Only one shutdown handler per
    script is allowed.

    Shutdown handlers:
    - Run when the script is unloaded, reloaded, or HA stops
    - Have a strict timeout (200ms by default) - must complete quickly
    - Will be forcefully terminated if they exceed the timeout
    - If an action is running when shutdown is requested, it will be cancelled first
    - Cannot be triggered manually from the UI
    - Are executed through the action worker pool

    Args:
        func: The function to mark as a shutdown handler.

    Returns:
        The decorated function.

    Example:
        @shutdown
        async def on_shutdown():
            log_info("Script shutting down...")
            # Clean up resources, save state, etc.
            # Keep it fast! Max 200ms allowed

        @shutdown
        def sync_shutdown():
            # Sync functions are also supported
            pass
    """
    ...

def set_status(message: str | None) -> None:
    """Set a status message for this script.

    This message is displayed in the UI when the script is running an action.
    The status is shown as: "Running <action_name> (<elapsed_time>): <message>"
    The status message is automatically cleared when the action completes.

    Call with None to clear the message without waiting for action completion.

    Args:
        message: The status message to display, or None to clear.

    Example:
        @action
        async def long_running_task():
            set_status("Starting...")
            await sleep(1)

            set_status("Processing items...")
            for i in range(100):
                set_status(f"Processing item {i + 1}/100")
                await sleep(0.1)

            set_status("Finishing up...")
            await sleep(1)
            # Status automatically cleared when action ends
    """
    ...

# =============================================================================
# Built-in globals available in HAAnim scripts
# These are injected into the script's namespace at runtime.
# =============================================================================

# Note: The following are NOT part of the 'haanim' module but are available
# as global variables in your scripts. They are documented here for reference.
#
# log: logging.Logger           - Logger instance for your script
# log_debug: Callable           - Shortcut for log.debug()
# log_info: Callable            - Shortcut for log.info()
# log_warning: Callable         - Shortcut for log.warning()
# log_error: Callable           - Shortcut for log.error()
# sleep: Callable[[float], Awaitable[None]]  - asyncio.sleep for delays
# set_status: Callable[[str | None], None]   - Set status message for UI
# hass: HomeAssistant           - Home Assistant instance (when available)
# state: StateManager           - Access entity states (when available)
