#!/usr/bin/env python3
"""Generate type stub file for the HAAnim virtual module.

This script generates the haanim.pyi stub file that provides type hints
for user automation scripts. The stub file enables IDE features like
autocompletion and type checking.

Usage:
    uv run python scripts/generate_stubs.py [output_path]

If no output path is specified, the stub is written to:
    podman/container-config/haanim/haanim.pyi
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path
from typing import Any, Callable

# Add the custom_components directory to the path
SCRIPT_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(SCRIPT_DIR))

from custom_components.haanim import decorators


STUB_HEADER = '''"""Type stubs for the HAAnim virtual module.

This file provides type hints for the 'haanim' module that is available
to user automation scripts. It allows IDE features like autocompletion,
type checking, and documentation to work properly.

Note: This module is virtual and provided by the HAAnim integration at runtime.
The actual implementations are in custom_components/haanim/decorators.py.

Auto-generated by: uv run python scripts/generate_stubs.py
"""

from typing import Any, Callable, TypeVar, overload

F = TypeVar("F", bound=Callable[..., Any])

# =============================================================================
# Decorators
# =============================================================================

'''

STUB_FOOTER = """

# =============================================================================
# Built-in globals available in HAAnim scripts
# These are injected into the script's namespace at runtime.
# =============================================================================

# Note: The following are NOT part of the 'haanim' module but are available
# as global variables in your scripts. They are documented here for reference.
#
# log: logging.Logger           - Logger instance for your script
# log_debug: Callable           - Shortcut for log.debug()
# log_info: Callable            - Shortcut for log.info()
# log_warning: Callable         - Shortcut for log.warning()
# log_error: Callable           - Shortcut for log.error()
# sleep: Callable[[float], Awaitable[None]]  - asyncio.sleep for delays
# hass: HomeAssistant           - Home Assistant instance (when available)
# state: StateManager           - Access entity states (when available)
"""


def get_decorator_signature(func: Callable[..., Any]) -> str:
    """Get the signature of a decorator function.

    Args:
        func: The decorator function.

    Returns:
        String representation of the function signature.
    """
    sig = inspect.signature(func)
    return str(sig)


def get_docstring(func: Callable[..., Any]) -> str:
    """Get the docstring of a function, properly indented.

    Args:
        func: The function to get the docstring from.

    Returns:
        Properly formatted docstring.
    """
    doc = inspect.getdoc(func)
    if not doc:
        return '    """No documentation available."""'

    lines = doc.split("\n")
    result = ['    """' + lines[0]]
    for line in lines[1:]:
        result.append("    " + line if line.strip() else "")
    result.append('    """')
    return "\n".join(result)


def generate_overloaded_decorator(name: str, func: Callable[..., Any]) -> str:
    """Generate stub for a decorator that can be used with or without arguments.

    Args:
        name: The decorator name.
        func: The decorator function.

    Returns:
        Stub code with overloads.
    """
    docstring = get_docstring(func)

    # Get the full signature
    sig = inspect.signature(func)
    params = list(sig.parameters.values())

    # Find keyword-only parameters
    kw_params = [p for p in params if p.kind == inspect.Parameter.KEYWORD_ONLY]

    # Build the overloaded signatures
    lines = []

    # Overload 1: @decorator (no parentheses)
    lines.append("@overload")
    lines.append(f"def {name}(func: F) -> F:")
    lines.append(f'    """Mark a function as a {name} (no arguments)."""')
    lines.append("    ...")
    lines.append("")
    lines.append("")

    # Overload 2: @decorator(...) with arguments
    lines.append("@overload")
    kw_sig_parts = []
    for p in kw_params:
        annotation = p.annotation if p.annotation != inspect.Parameter.empty else "Any"
        if isinstance(annotation, type):
            annotation = annotation.__name__
        else:
            annotation = str(annotation).replace("typing.", "")
        default = f" = {p.default!r}" if p.default != inspect.Parameter.empty else ""
        kw_sig_parts.append(f"    {p.name}: {annotation}{default},")

    if kw_sig_parts:
        lines.append(f"def {name}(")
        lines.append("    name: str | None = None,")
        lines.append("    *,")
        lines.extend(kw_sig_parts)
        lines.append(") -> Callable[[F], F]:")
    else:
        lines.append(f"def {name}(")
        lines.append("    name: str | None = None,")
        lines.append(") -> Callable[[F], F]:")

    lines.append(f'    """Expose a function as a {name} with configuration."""')
    lines.append("    ...")
    lines.append("")
    lines.append("")

    # Main signature (combines both)
    lines.append(f"def {name}(")
    lines.append("    name_or_func: str | F | None = None,")
    if kw_sig_parts:
        lines.append("    *,")
        lines.extend(kw_sig_parts)
    lines.append(") -> F | Callable[[F], F]:")
    lines.append(docstring)
    lines.append("    ...")

    return "\n".join(lines)


def generate_simple_decorator(name: str, func: Callable[..., Any]) -> str:
    """Generate stub for a simple decorator (always requires parentheses).

    Args:
        name: The decorator name.
        func: The decorator function.

    Returns:
        Stub code.
    """
    sig = inspect.signature(func)
    params = list(sig.parameters.values())
    docstring = get_docstring(func)

    lines = [f"def {name}("]

    # Track if we've added keyword-only separator or have *args
    added_kw_separator = False
    has_var_positional = any(p.kind == inspect.Parameter.VAR_POSITIONAL for p in params)

    for p in params:
        annotation = p.annotation if p.annotation != inspect.Parameter.empty else "Any"
        if isinstance(annotation, type):
            annotation = annotation.__name__
        else:
            annotation = str(annotation).replace("typing.", "")

        if p.kind == inspect.Parameter.VAR_POSITIONAL:
            lines.append(f"    *{p.name}: {annotation},")
            added_kw_separator = True  # *args implies keyword-only for following params
        elif p.kind == inspect.Parameter.VAR_KEYWORD:
            lines.append(f"    **{p.name}: {annotation},")
        elif p.kind == inspect.Parameter.KEYWORD_ONLY:
            # Add keyword-only separator only if no *args and not already added
            if not added_kw_separator and not has_var_positional:
                lines.append("    *,")
                added_kw_separator = True
            default = ""
            if p.default != inspect.Parameter.empty:
                if p.default is None:
                    default = " = None"
                elif isinstance(p.default, bool):
                    default = f" = {p.default}"
                else:
                    default = f" = {p.default!r}"
            lines.append(f"    {p.name}: {annotation}{default},")
        else:
            default = ""
            if p.default != inspect.Parameter.empty:
                if p.default is None:
                    default = " = None"
                else:
                    default = f" = {p.default!r}"
            lines.append(f"    {p.name}: {annotation}{default},")

    lines.append(") -> Callable[[F], F]:")
    lines.append(docstring)
    lines.append("    ...")

    return "\n".join(lines)


def generate_stubs() -> str:
    """Generate the complete stub file content.

    Returns:
        The complete stub file as a string.
    """
    parts = [STUB_HEADER]

    # Decorators that support both @decorator and @decorator() syntax
    overloaded_decorators = ["scene", "service"]

    # Simple decorators that require parentheses
    simple_decorators = [
        "state_trigger",
        "time_trigger",
        "event_trigger",
        "time_active",
        "state_active",
    ]

    for name in overloaded_decorators:
        func = getattr(decorators, name)
        parts.append(generate_overloaded_decorator(name, func))
        parts.append("")
        parts.append("")

    for name in simple_decorators:
        func = getattr(decorators, name)
        parts.append(generate_simple_decorator(name, func))
        parts.append("")
        parts.append("")

    parts.append(STUB_FOOTER)

    return "\n".join(parts)


def main() -> int:
    """Main entry point.

    Returns:
        Exit code (0 for success).
    """
    parser = argparse.ArgumentParser(description="Generate type stub file for the HAAnim virtual module.")
    parser.add_argument(
        "output",
        nargs="?",
        default=None,
        help="Output path for the stub file (default: stubs/haanim.pyi and container config)",
    )
    args = parser.parse_args()

    # Generate the stub content
    content = generate_stubs()

    if args.output:
        # Single output path specified
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content)
        print(f"Generated stub file: {output_path}")
    else:
        # Default: generate to multiple locations
        outputs = [
            SCRIPT_DIR / "stubs" / "haanim.pyi",
            SCRIPT_DIR / "podman" / "container-config" / "haanim" / "haanim.pyi",
        ]
        for output_path in outputs:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(content)
            print(f"Generated stub file: {output_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
